 server:
  port: 8082

spring:
  application:
    name: auth-service

  # Environment-based profiles configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  # Use PostgreSQL by default (no H2)
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres-auth}:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth_service}
    username: ${POSTGRES_USER:smartdrive}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            redirect-uri: "{baseUrl}/oauth2/social/google/callback"
            scope: openid, profile, email

# Authentication Service Configuration
auth:
  service:
    name: SmartDrive Auth Service
    version: 1.0.0

  jwt:
    # JWT token configuration
    access-token-expiry: 1800 # 30 minutes
    refresh-token-expiry: 604800 # 7 days

  security:
    # Security settings that can be overridden per environment
    enforce-email-verification: true
    max-failed-login-attempts: 5
    account-lockout-duration: 3600 # 1 hour

  integration:
    user-service:
      url: ${USER_SERVICE_URL:http://user-service:8083}
      timeout: 5000

# Service URLs for inter-service communication
user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8083}

# Internal service authentication
gateway:
  signature:
    secret: ${GATEWAY_SIGNATURE_SECRET:signature-gateway-secret-key-2024-minimum-32-chars}
  internal:
    auth:
      key: ${GATEWAY_INTERNAL_SECRET:internal-gateway-secret-key-2024-minimum-32-chars}

# Logging configuration
logging:
  level:
    com.smartdrive.authservice: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

auth:
  security:
    # More permissive settings for development
    enforce-email-verification: false # Allow login without email verification in dev
    max-failed-login-attempts: 10

logging:
  level:
    com.smartdrive.authservice: DEBUG
    org.springframework.security: DEBUG
    root: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # Don't auto-update schema in production

auth:
  security:
    # Strict security settings for production
    enforce-email-verification: true
    max-failed-login-attempts: 3
    account-lockout-duration: 7200 # 2 hours

logging:
  level:
    com.smartdrive.authservice: INFO
    org.springframework.security: WARN
    root: WARN
